version: "3"
services:
  grafana_agent:
    image: grafana_collector_local_image:latest
    environment:
      STACK_NAME: cminformatiktest
      AZURE_ENV_NAME: "Test"
      SITE_NAME: Local-Testing
      AGENT_NAME: Local-Testing-Agent
      AZURE_CLIENT_ID: this-is-just-a-placeholder
      LOG_LEVEL: debug
      AZURE_SUBSCRIPTION_ID: 12345678-1234-1234-1234-123456789012
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    env_file:
      - .\local_configuration.env
