version: "3"
services:
  grafana_agent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      STACK_NAME: cminformatiktest
      AZURE_ENV_NAME: "Test"
      SITE_NAME: Local-Testing
      AGENT_NAME: Local-Testing-Agent
      AZURE_CLIENT_ID: this-is-just-a-placeholder
      LOG_LEVEL: debug
      AZURE_SUBSCRIPTION_ID: 12345678-1234-1234-1234-123456789012
      ENABLE_AZURE_AUTODISCOVERY: true
      ENABLE_OPENTELEMETRY_RECEIVER: true
      OPENTELEMETRY_ATTRIBUTE_ENVIRONMENT: "Development"
      ENABLE_PUSH_GATEWAY: true
      ENABLE_FORWARDERS: true

    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
      - 9091:9091
    env_file:
      - .\local_configuration.env
