FROM grafana/agent:latest

COPY ./azure_grafana_agent/entrypoint.sh /bin/entrypoint.sh
COPY ./azure_grafana_agent/config.river /etc/agent/config.river

RUN chmod +x /bin/entrypoint.sh

ENTRYPOINT ["/bin/entrypoint.sh"]

