name: PR von Codeowner reviewed

on:
  pull_request:
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  codeowners:
    runs-on: ubuntu-latest
    env:
      codeowners_metatool: "borgiman;gregorbosshard;urva;Matthias-Hess;fdc-cmi;EliaSaSe;bschaeublin;cmiagmbu;cmiagika;HeinzBiglerCMI;DenoshanRajasingam;Luca-Guettinger;jweiss27;juergotter;andreaszingg;marco554;LukasMerz;OliverBecker92;PhilipCereto;cmimar01;SimonSchwendele;cmiagpsc;rstadler6;tweakch;ArmandoShala"
    if: ${{ (github.event.review.state == 'approved')}}
    steps:
      - name: Check Codeowners
        if: true && !contains(env.codeowners_metatool, github.event.review.user.login)
        run: |
          echo "Review muss von einem Codeowner durchgeführt werden" 
          exit 1
