name: Pre-Merge Validates
on: 
  pull_request:
    branches:  
      - develop
      
jobs:
  pre_merge_validates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run dotnet format
        run: |
          mapfile -t modified_files < <(gh pr view --json files -q '.files[].path')
          dotnet format whitespace "$(find . -name *.sln | head -n1)" --verify-no-changes --no-restore --include "${modified_files[@]}"
